#!/bin/bash

./mktestenvconfig || exit 1
. testenv_config

# docker rm relay; docker run --privileged --name relay -it -v ${SLITHEEN_CODE_REPO}:/home/iang/slitheen_code slitheen /bin/bash -c 'echo "Waiting for veth to appear..."; while ! ifconfig veth1 >/dev/null 2>&1; do sleep 1; done; sleep 1; cd slitheen_code/relay_station && bash'
docker rm relay; docker run --privileged --name relay -it -v ${SLITHEEN_RELAY_REPO}:/home/iang/relay slitheen /bin/bash -c 'cd relay && bash'
