#!/bin/bash

container_name="relay_$(whoami)"

./mktestenvconfig || exit 1
. testenv_config

docker rm $container_name 2>&1; 
docker run --privileged --name $container_name -it -v ${SLITHEEN_RELAY_REPO}:/home/slitheen/relay slitheen /bin/bash -c 'cd relay && bash'
